# Generated by Django 5.1.7 on 2025-05-12 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recuperar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('curp', models.CharField(max_length=18)),
                ('contrasena', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('colonia', models.CharField(max_length=100)),
                ('discapacidad', models.CharField(default='No', max_length=2)),
                ('CURP', models.CharField(max_length=18, unique=True)),
                ('estado_nacimiento', models.CharField(default='desconocido', max_length=30)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('aviso_privacidad', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('colonia', models.CharField(max_length=100)),
                ('discapacidad', models.CharField(max_length=2)),
                ('actividad', models.CharField(max_length=20)),
                ('fecha_hora', models.DateTimeField()),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('estado_nacimiento', models.CharField(default='desconocido', max_length=30)),
                ('aviso_privacidad', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visitausuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('colonia', models.CharField(max_length=100)),
                ('discapacidad', models.CharField(default='no', max_length=2)),
                ('CURP', models.CharField(max_length=18)),
                ('estado_nacimiento', models.CharField(max_length=30)),
                ('actividad', models.CharField(max_length=50)),
                ('fecha_visita', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visitas.registrousuario')),
            ],
        ),
    ]
